# Generated by Django 4.0.5 on 2022-07-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('latc', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longc', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat1', models.DecimalField(decimal_places=8, max_digits=11)),
                ('long1', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat2', models.DecimalField(decimal_places=8, max_digits=11)),
                ('long2', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat3', models.DecimalField(decimal_places=8, max_digits=11)),
                ('long3', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latc4', models.DecimalField(decimal_places=8, max_digits=11)),
                ('long4', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.AlterField(
            model_name='car_x',
            name='vehicle',
            field=models.CharField(choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4')], max_length=8, unique=True),
        ),
    ]
