# Generated by Django 4.0.5 on 2022-07-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0002_inter_alter_car_x_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter',
            name='name',
            field=models.CharField(default='TEST', max_length=8, unique=True),
        ),
    ]
