# Generated by Django 4.0.5 on 2022-07-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0003_alter_inter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter',
            name='lat1',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='lat2',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='lat3',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='latc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='latc4',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='long1',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='long2',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='long3',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='long4',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='inter',
            name='longc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
