# Generated by Django 4.0.5 on 2022-07-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0004_alter_inter_lat1_alter_inter_lat2_alter_inter_lat3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inter',
            old_name='latc4',
            new_name='lat4',
        ),
    ]
